name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
    steps:
      - name: Log Node & OS version
        run: |
          node -v
          cat /etc/os-release 
      - name: Log env
        run: echo $API_URL 
      - name: create a file
        run: echo 'Some text' > text.txt   
      - name: Container in a step
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /usr/local/bin/node 
          args: -p 2+34
      - name: Log node version
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /usr/local/bin/node 
          args: -v
      - name: show file container
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat 
          args: text.txt  
      - uses: actions/checkout@v3
      - name: Give permission
        run: chmod +x script.sh

      - name: Run a bash script
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: sh
          args: script.sh "some string" 
      - name: Send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: From Github Actions
          SLACK_MESSAGE: "Actor:${{github}}, Event: ${{github.event_name}}, Workflow: ${{github.workflow}}, Job: ${{github.job}}"
          SLACK_COLOR: "#723fc4"


