name: Variables and Secrets
on: [push]
jobs:
  display-vars-and-secrets:
    runs-on: ubuntu-latest
    env:
      BOOLEAN_SECRETE: ${{ secrets.BOOLEAN_SECRETE}}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR}}
      REPO_LEVEL_VAR: ${{vars.REPO_LEVEL_VAR}}
    steps:
        - name: Runs only if BOOLEAN_SECRETE is true
          if: env.BOOLEAN_SECRETE == 'true'
          run: echo "BOOLEAN_SE
        - name: Log Vars
          run: |
            echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
            echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"    