name: Variables and Secrets
on: [push]
jobs:
  decrept-file:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Decrypt file
          env:
            PASSPHRASE: ${{ secrets.PASSPHRASE }}
          run: |
            mkdir -p secrets
            gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output secrets/secret.json secret.json.gpg
        - name: View Encrypted file(NEVER DO THIS IN REAL PROJECTS)
          run: cat secrets/secret.json

  display-vars-and-secrets:
    runs-on: ubuntu-latest
    environment: "stagging"
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET}}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR}}
      REPO_LEVEL_VAR: ${{vars.REPO_LEVEL_VAR}}
    steps:
        - name: Runs only if BOOLEAN_SECRET is true
          if: contains(env.BOOLEAN_SECRET, 'true')
          run: echo "BOOLEAN_SECRET"
        - name: Log Vars
          run: |
            echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
            echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"   
            echo "ENV_LEVEL_VAR from context: $ENV_LEVEL_VAR" 